# vim: set ft=ansible:
---

- name: Create Filebeat SSL Directory
  ansible.builtin.file:
    name: "/etc/filebeat/ssl"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy Filebeat Client Certificate
  ansible.builtin.copy:
    src: "etc/filebeat/ssl/client.crt"
    dest: "/etc/filebeat/ssl/client.crt"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Copy Filebeat Client Key
  ansible.builtin.copy:
    src: "etc/filebeat/ssl/client.key"
    dest: "/etc/filebeat/ssl/client.key"
    mode: "0640"
    owner: "root"
    group: "root"

- name: Create Filebeat configuration file
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0640"
  with_items:
    - "etc/filebeat/filebeat.yml"

- name: Add certificate location to glob file
  ansible.builtin.lineinfile:
    dest: "{{ SITE.cert_glob_file }}"
    owner: root
    group: root
    mode: "0644"
    create: yes
    line: "/etc/filebeat/ssl/client.crt"
  when: SITE.cert_glob_file is defined
