---
# skip idempotence tests
- name: Include Filebeat intall
  when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  ansible.builtin.include_role:
    name: filebeat

# skip idempotence tests
- name: Prepare Dummy SSL Key / Certifcate
  when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  delegate_to: localhost
  block:
    # Required for community.crypto.openssl_privatekey / x509_certificate
    - name: Install cryptography python package
      ansible.builtin.pip:
        name: cryptography

    - name: Include vars of defaults/main.yml
      ansible.builtin.include_vars:
        file: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"
        name: _defaults

    - name: Create files/etc/filebeat/ssl directory
      ansible.builtin.file:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/files/etc/filebeat/ssl/"
        state: directory
        recurse: true
        mode: "0755"

    - name: Generate etc/filebeat/ssl/client.key
      community.crypto.openssl_privatekey:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/files/etc/filebeat/ssl/client.key"
        passphrase: "{{ _defaults._filebeat.ssl.key_passphrase }}"
        size: 2048
        cipher: auto
        mode: "0644"

    - name: Generate etc/filebeat/ssl/client.crt
      community.crypto.x509_certificate:
        path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/files/etc/filebeat/ssl/client.crt"
        privatekey_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/files/etc/filebeat/ssl/client.key"
        privatekey_passphrase: "{{ _defaults._filebeat.ssl.key_passphrase }}"
        provider: selfsigned
        mode: "0644"
